import { NextResponse } from "next/server";
import { affiliateFlagEnabled,splitRiskReserve } from "@/modules/affiliate";
import { getSupabaseAdminClient } from "@/lib/supabase/admin";

export async function POST(request:Request){
  if(!affiliateFlagEnabled(process.env,"AFFILIATE_COMMISSION_REAL")) return NextResponse.json({error:"Not found."},{status:404});
  const secret=process.env.AFFILIATE_OUTBOX_CRON_SECRET;if(!secret||request.headers.get("authorization")!==`Bearer ${secret}`) return NextResponse.json({error:"Unauthorized."},{status:401});
  const admin=getSupabaseAdminClient();const {data:reconciliation}=await admin.from("affiliate_reconciliations").select("status").eq("program_id","secwyn-india").order("reconciliation_date",{ascending:false}).limit(1).maybeSingle();if(reconciliation?.status!=="matched") return NextResponse.json({error:"Reconciliation gate is closed."},{status:409});
  const {data:incidents}=await admin.from("affiliate_integrity_incidents").select("id").eq("program_id","secwyn-india").in("severity",["high","critical"]).in("status",["open","contained"]).limit(1);if(incidents?.length) return NextResponse.json({error:"Integrity incident gate is closed."},{status:409});
  const {data:schedules,error}=await admin.from("affiliate_commission_schedules").select("id,installment,release_at,amount_minor,affiliate_commission_decisions!inner(id,program_id,affiliate_id,status,affiliate_sales!inner(status))").eq("status","held").eq("affiliate_commission_decisions.program_id","secwyn-india").eq("affiliate_commission_decisions.status","held").eq("affiliate_commission_decisions.affiliate_sales.status","qualified").lte("release_at",new Date().toISOString()).limit(100);if(error) return NextResponse.json({error:"Reserve release unavailable."},{status:503});
  const released=[];for(const schedule of schedules||[]){const decision=Array.isArray(schedule.affiliate_commission_decisions)?schedule.affiliate_commission_decisions[0]:schedule.affiliate_commission_decisions;if(!decision) continue;const amount=BigInt(schedule.amount_minor);const first=splitRiskReserve(amount);const releaseAt=Date.parse(schedule.release_at);const candidates=schedule.installment===0?[{key:"day30",amount:first.day30.amountMinor,due:releaseAt},{key:"day60",amount:first.day60.amountMinor,due:releaseAt+30*86400000}]:[{key:"full",amount,due:releaseAt}];for(const candidate of candidates){if(candidate.due>Date.now()||candidate.amount===0n) continue;const {error:writeError}=await admin.from("affiliate_ledger_entries").upsert({program_id:"secwyn-india",affiliate_id:decision.affiliate_id,decision_id:decision.id,entry_type:"reserve_release",currency:"USD",amount_minor:candidate.amount.toString(),effective_at:new Date(candidate.due).toISOString(),posting_state:"payable",idempotency_key:`release:${schedule.id}:${candidate.key}`,correlation_id:crypto.randomUUID(),metadata:{scheduleId:schedule.id,installment:schedule.installment,reserveStage:candidate.key}},{onConflict:"program_id,idempotency_key"});if(writeError) return NextResponse.json({error:"Reserve release write failed."},{status:503});released.push(`${schedule.id}:${candidate.key}`);}}
  return NextResponse.json({released:released.length});
}
