import { NextResponse } from "next/server";
import { affiliateFlagEnabled,calculateCommission,multiplyRatioHalfUp,parseUsdDecimal,resolveProgramRuleVersion,serializeMoney,usd,type AffiliatePlan,type BillingInterval } from "@/modules/affiliate";
import { auditCommission } from "@/modules/affiliate/domain/audit-calculator";
import { canonicalAffiliateCustomerId } from "@/modules/affiliate/application/attribution";
import { getSupabaseAdminClient } from "@/lib/supabase/admin";
import { findCreemProductById } from "@/lib/creem";

type PaymentFact={eventType?:string;providerEventId?:string;userId?:string;transactionId?:string;refundAmountMinor?:number|null;occurredAt?:string};
const SUCCEEDED=new Set(["checkout.completed","subscription.active","subscription.paid"]);
const REVERSALS=new Set(["refund.created","dispute.created"]);

export async function POST(request:Request){
  if(!affiliateFlagEnabled(process.env,"AFFILIATE_COMMISSION_SHADOW")) return NextResponse.json({error:"Not found."},{status:404});
  const expected=process.env.AFFILIATE_OUTBOX_CRON_SECRET;if(!expected||request.headers.get("authorization")!==`Bearer ${expected}`) return NextResponse.json({error:"Unauthorized."},{status:401});
  const admin=getSupabaseAdminClient();const worker=`shadow:${crypto.randomUUID()}`;const {data:events,error}=await admin.rpc("affiliate_claim_outbox",{p_worker:worker,p_limit:25});if(error) return NextResponse.json({error:"Outbox claim failed."},{status:503});
  const results=[];
  for(const event of events||[]){
    try{
      const fact=event.payload as PaymentFact;
      if(REVERSALS.has(fact.eventType||"")){
        if(!fact.providerEventId||!fact.transactionId) throw new Error("AFFILIATE_REVERSAL_FACT_INCOMPLETE");
        const {data:sale,error:saleError}=await admin.from("affiliate_sales").select("id,gross_amount_minor,status,affiliate_attributions!inner(affiliate_id),affiliate_commission_decisions(id,amount_minor,status)").eq("program_id","secwyn-india").eq("provider","creem").eq("provider_transaction_id",fact.transactionId).maybeSingle();
        if(saleError) throw saleError;if(!sale){await admin.from("affiliate_outbox_events").update({status:"processed",processed_at:new Date().toISOString()}).eq("id",event.id);continue;}
        const attribution=Array.isArray(sale.affiliate_attributions)?sale.affiliate_attributions[0]:sale.affiliate_attributions;const decision=Array.isArray(sale.affiliate_commission_decisions)?sale.affiliate_commission_decisions[0]:sale.affiliate_commission_decisions;
        if(!attribution?.affiliate_id||!decision?.id) throw new Error("AFFILIATE_REVERSAL_DECISION_NOT_FOUND");
        const reversalType=fact.eventType==="dispute.created"?"chargeback":"refund";const grossMinor=BigInt(sale.gross_amount_minor);const reversedGross=reversalType==="chargeback"?grossMinor:BigInt(fact.refundAmountMinor||0);if(reversedGross<=0n) throw new Error("AFFILIATE_REFUND_AMOUNT_UNVERIFIED");const clawback=multiplyRatioHalfUp(usd(BigInt(decision.amount_minor)),reversedGross>grossMinor?grossMinor:reversedGross,grossMinor).amountMinor;const postingState=decision.status==="shadow"?"shadow":"payable";const {error:reversalError}=await admin.rpc("affiliate_record_reversal",{p_program_id:"secwyn-india",p_sale_id:sale.id,p_affiliate_id:attribution.affiliate_id,p_decision_id:decision.id,p_provider_event_id:fact.providerEventId,p_reversal_type:reversalType,p_reversed_gross_minor:reversedGross.toString(),p_clawback_minor:clawback.toString(),p_posting_state:postingState,p_correlation_id:event.id});if(reversalError) throw reversalError;
        await admin.from("affiliate_outbox_events").update({status:"processed",processed_at:new Date().toISOString()}).eq("id",event.id);results.push({id:event.id,status:"shadow_reversed"});continue;
      }
      if(!SUCCEEDED.has(fact.eventType||"")){await admin.from("affiliate_outbox_events").update({status:"processed",processed_at:new Date().toISOString()}).eq("id",event.id);continue;}
      if(!fact.userId||!fact.providerEventId||!fact.transactionId||!fact.occurredAt) throw new Error("AFFILIATE_PAYMENT_FACT_INCOMPLETE");
      const {data:payment,error:paymentError}=await admin.from("payments").select("user_id,provider_product_id,amount,currency,status").eq("provider","creem").eq("provider_transaction_id",fact.transactionId).maybeSingle();
      if(paymentError||!payment) throw new Error("AFFILIATE_CANONICAL_PAYMENT_NOT_FOUND");
      if(payment.status!=="completed"||payment.user_id!==fact.userId||String(payment.currency||"").toUpperCase()!=="USD"||payment.amount===null) throw new Error("AFFILIATE_CANONICAL_PAYMENT_INVALID");
      const product=findCreemProductById(payment.provider_product_id);if(!product||!["starter","growth","scale"].includes(product.plan)) throw new Error("AFFILIATE_CANONICAL_PRODUCT_INVALID");
      const plan=product.plan as AffiliatePlan;const billingInterval=(product.billingInterval==="yearly"?"annual":"monthly") as BillingInterval;const grossMinor=parseUsdDecimal(String(payment.amount)).amountMinor;
      const customer=canonicalAffiliateCustomerId(payment.user_id);const {data:attribution}=await admin.from("affiliate_attributions").select("id,affiliate_id,generation,expires_at,affiliate_memberships!inner(status,user_id)").eq("program_id","secwyn-india").eq("canonical_customer_id",customer).eq("generation",1).gte("expires_at",fact.occurredAt).single();if(!attribution) throw new Error("AFFILIATE_ATTRIBUTION_NOT_FOUND");
      const membership=Array.isArray(attribution.affiliate_memberships)?attribution.affiliate_memberships[0]:attribution.affiliate_memberships;if(!membership||!['provisional','approved'].includes(membership.status)) throw new Error("AFFILIATE_MEMBERSHIP_INELIGIBLE");if(membership.user_id===payment.user_id) throw new Error("AFFILIATE_SELF_REFERRAL");
      const {data:priorSale,error:priorSaleError}=await admin.from("affiliate_sales").select("id,status").eq("program_id","secwyn-india").eq("provider","creem").eq("provider_transaction_id",fact.transactionId).maybeSingle();if(priorSaleError) throw priorSaleError;if(priorSale&&["refunded","chargeback","reversed"].includes(priorSale.status)){await admin.from("affiliate_outbox_events").update({status:"processed",processed_at:new Date().toISOString()}).eq("id",event.id);results.push({id:event.id,status:"terminal_sale_ignored"});continue;}
      const sale={id:priorSale?.id||crypto.randomUUID()};
      const rule=resolveProgramRuleVersion("secwyn-india",fact.occurredAt,process.env.AFFILIATE_PROGRAM_LAUNCH_START_AT);const {data:storedRule}=await admin.from("affiliate_rule_versions").select("id").eq("program_id","secwyn-india").eq("version",rule.version).eq("status","published").lte("effective_from",fact.occurredAt).or(`effective_until.is.null,effective_until.gt.${fact.occurredAt}`).single();if(!storedRule) throw new Error("AFFILIATE_STORED_RULE_NOT_FOUND");const primary=calculateCommission({saleId:sale.id,providerEventId:fact.providerEventId,programId:"secwyn-india",affiliateId:attribution.affiliate_id,canonicalCustomerId:customer,plan,interval:billingInterval,paidAt:fact.occurredAt,gross:{amountMinor:grossMinor,currency:"USD"},refundedMinor:0n,chargeback:false,selfReferral:false,attributionGeneration:1},rule,true);const audit=auditCommission({phase:rule.phase,plan,interval:billingInterval,paidAt:fact.occurredAt});
      const schedule=primary.schedule.map((item)=>({releaseAt:item.releaseAt,amount:serializeMoney(item.amount)}));const auditSchedule=audit.schedule.map((item)=>({releaseAt:item.releaseAt,amount:serializeMoney(item.amount)}));
      const real=affiliateFlagEnabled(process.env,"AFFILIATE_COMMISSION_REAL");const {error:decisionError}=await admin.rpc("affiliate_record_sale_decision",{p_mode:real?"real":"shadow",p_sale_id:sale.id,p_program_id:"secwyn-india",p_attribution_id:attribution.id,p_provider:"creem",p_provider_transaction_id:fact.transactionId,p_canonical_customer_id:customer,p_plan:plan,p_billing_interval:billingInterval,p_gross_amount_minor:grossMinor.toString(),p_paid_at:fact.occurredAt,p_raw_event_ref:fact.providerEventId,p_decision_id:primary.decisionId,p_affiliate_id:attribution.affiliate_id,p_rule_version_id:storedRule.id,p_amount_minor:primary.amount.amountMinor.toString(),p_reason:real?"RESERVE_PERIOD":primary.reason,p_schedule:schedule,p_fingerprint:primary.fingerprint,p_calculator_version:"affiliate-core-v1",p_audit_amount_minor:audit.amount.amountMinor.toString(),p_audit_schedule:auditSchedule,p_correlation_id:event.id});if(decisionError) throw decisionError;
      await admin.from("affiliate_outbox_events").update({status:"processed",processed_at:new Date().toISOString()}).eq("id",event.id);results.push({id:event.id,status:real?"held_recorded":"shadow_recorded"});
    }catch(error){const attempts=Number(event.attempt_count||1);const message=error instanceof Error?error.message:"AFFILIATE_SHADOW_FAILED";if(attempts>=5){await admin.from("affiliate_outbox_events").update({status:"dead_letter"}).eq("id",event.id);await admin.from("affiliate_dead_letters").upsert({outbox_event_id:event.id,reason:message,payload:event.payload},{onConflict:"outbox_event_id"});}else await admin.from("affiliate_outbox_events").update({status:"pending",available_at:new Date(Date.now()+Math.min(3600,30*2**attempts)*1000).toISOString(),locked_at:null,locked_by:null}).eq("id",event.id);results.push({id:event.id,status:attempts>=5?"dead_letter":"retry"});}
  }
  return NextResponse.json({processed:results.length,results});
}
