import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { affiliateFlagEnabled } from "@/modules/affiliate";
import {
  loadAffiliateApplicationState,
  loadAffiliateBalance,
  loadAffiliateMembership,
  loadAffiliateWorkspace,
  requireAffiliateUser,
} from "@/modules/affiliate/application/server";

function money(minor:string|number|bigint){return `$${(Number(minor)/100).toFixed(2)}`;}

export default async function AffiliatePortalPage() {
  if (!affiliateFlagEnabled(process.env, "AFFILIATE_PROVISIONAL_ACTIVATION")) notFound();
  let user;
  try { user = await requireAffiliateUser(); } catch { redirect("/login?next=/affiliate/portal"); }
  const [membership,application]=await Promise.all([loadAffiliateMembership(user.id),loadAffiliateApplicationState(user.id)]);
  const balance = membership ? await loadAffiliateBalance(membership.id) : 0n;
  const workspace=membership?await loadAffiliateWorkspace(membership.id):null;
  const actionTypes=new Set((workspace?.actions||[]).map((item)=>item.action_type));
  const formats=new Set((workspace?.actions||[]).map((item)=>item.format));
  const shortcut=(workspace?.events||[]).find((item)=>["referred_registration","verified_opportunity","first_payment"].includes(item.event_type));
  return <main className="mx-auto min-h-screen max-w-6xl px-6 py-12 text-slate-900 dark:text-slate-100">
    <p className="text-xs font-semibold uppercase tracking-[.25em]">Affiliate Portal</p>
    <div className="mt-4 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-4xl font-semibold">Your Secwyn affiliate workspace</h1><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">India program · independent and commission-only</p></div>{membership?.status==="approved"&&<span className="rounded-full border border-amber-400 bg-amber-50 px-4 py-2 text-xs font-semibold uppercase tracking-[.16em] text-amber-900 dark:bg-amber-950/30 dark:text-amber-200">India Founding Affiliate</span>}</div>
    {!membership ? <section className="mt-8 rounded-3xl border border-slate-300 p-7 dark:border-slate-700"><h2 className="text-xl font-semibold">{application?"Application received":"No application yet"}</h2><p className="mt-2 text-slate-600 dark:text-slate-300">{application?`Review status: ${application.status}. Latest policy quiz: ${application.quiz?.score??0}/5${application.quiz?.passed?" · passed":" · retry required"}.`:"Complete the India application and five-question policy confirmation to begin review."}</p>{!application&&<Link className="mt-5 inline-flex rounded-full border border-slate-400 px-5 py-2 text-sm font-semibold" href="/affiliate/india/apply">Start application</Link>}</section> : <>
      <div className="mt-8 grid gap-5 md:grid-cols-3"><section className="rounded-3xl border border-slate-300 p-6 dark:border-slate-700"><p className="text-sm text-slate-500">Status</p><p className="mt-2 text-2xl font-semibold capitalize">{membership.status}</p><p className="mt-2 text-xs text-slate-500">Provisional review lasts seven days. One three-day grace may be approved after expiry.</p></section><section className="rounded-3xl border border-slate-300 p-6 dark:border-slate-700"><p className="text-sm text-slate-500">USD ledger balance</p><p className="mt-2 text-2xl font-semibold">{money(balance)}</p><p className="mt-2 text-xs text-slate-500">Not payable until reserve, reconciliation and payout gates pass.</p></section><section className="rounded-3xl border border-slate-300 p-6 dark:border-slate-700"><p className="text-sm text-slate-500">Affiliate code</p><p className="mt-2 font-mono text-lg">{membership.affiliate_code}</p><Link href={`/a/${membership.affiliate_code}`} className="mt-3 inline-flex text-sm underline">Open referral link</Link></section></div>
      <div className="mt-8 grid gap-5 lg:grid-cols-2"><section className="rounded-3xl border border-slate-300 p-6 dark:border-slate-700"><h2 className="text-xl font-semibold">Activation progress</h2><p className="mt-3 text-sm">{actionTypes.size}/3 valid actions · {formats.size}/2 formats</p><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{shortcut?`Early activation evidence: ${shortcut.event_type.replaceAll("_"," ")}.`:"A valid referred registration, verified opportunity or first payment can complete activation early."}</p><p className="mt-3 text-xs text-slate-500">Provisional end: {membership.provisional_ends_at?new Date(membership.provisional_ends_at).toLocaleString("en-IN"):"Not set"} · Grace: {membership.grace_used_at?"used":"available once after expiry"}</p></section><section className="rounded-3xl border border-slate-300 p-6 dark:border-slate-700"><h2 className="text-xl font-semibold">Direct relationships only</h2><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">Only people you directly referred appear here. Downstream private data and downstream commission are never exposed.</p><ul className="mt-4 space-y-2 text-sm">{(workspace?.directRelationships||[]).length?(workspace?.directRelationships||[]).map((row,index)=><li key={index} className="rounded-2xl bg-slate-100 px-4 py-3 dark:bg-slate-900">Direct affiliate · relationship recorded {new Date(row.created_at).toLocaleDateString("en-IN")}</li>):<li className="text-slate-500">No direct affiliate relationship yet.</li>}</ul></section></div>
      <div className="mt-8 grid gap-5 lg:grid-cols-2"><section className="rounded-3xl border border-slate-300 p-6 dark:border-slate-700"><h2 className="text-xl font-semibold">Content resources & training</h2><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">Only approved, published program material is shown.</p><ul className="mt-4 space-y-2 text-sm">{(workspace?.resources||[]).slice(0,8).map((item)=><li key={item.id} className="rounded-2xl border border-slate-200 px-4 py-3 dark:border-slate-800">{item.content_key.replaceAll("_"," ")}</li>)}</ul><p className="mt-4 text-xs text-slate-500">Telegram updates remain subject to channel consent and publication controls.</p></section><section className="rounded-3xl border border-slate-300 p-6 dark:border-slate-700"><h2 className="text-xl font-semibold">Payout readiness</h2><p className="mt-2 text-sm">Manual Payoneer · USD ledger · $50 minimum · monthly review on the 28th.</p><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">PIN, OTP and recent reauthentication are required. A payout-account change starts a 72-hour freeze. INR is approximate display only.</p><p className="mt-4 text-sm">Account: {workspace?.payoutAccount?`${workspace.payoutAccount.provider} · ${workspace.payoutAccount.status}`:"Not configured"}</p><p className="mt-2 text-xs text-slate-500">States: Pending · Approved · Paid · Reconciled · Failed · Retry · Clawback</p></section></div>
    </>}
    <section className="mt-8 rounded-3xl border border-amber-300 bg-amber-50 p-6 dark:border-amber-800 dark:bg-amber-950/20"><h2 className="font-semibold">Shadow-mode safety</h2><p className="mt-2 text-sm">Real commission and payout remain disabled until reconciliation evidence and HumanOps gates are complete.</p></section>
  </main>;
}
