"use client";
import { useEffect,useState } from "react";

type Version={id:string;version:number;status:string;body:Record<string,unknown>;publish_at?:string};
type Item={id:string;content_key:string;content_type:string;locale:string;affiliate_content_versions:Version[]};

export default function AffiliateContentEditor(){
  const [items,setItems]=useState<Item[]>([]);const [key,setKey]=useState("");const [type,setType]=useState("approved_script");const [body,setBody]=useState('{"body":""}');const [message,setMessage]=useState("");
  async function load(){const response=await fetch("/api/admin/affiliate/content");const payload=await response.json();setItems(payload.items||[]);}
  useEffect(()=>{let active=true;void fetch("/api/admin/affiliate/content").then((response)=>response.json()).then((payload)=>{if(active)setItems(payload.items||[]);});return()=>{active=false;};},[]);
  async function create(event:React.FormEvent){event.preventDefault();try{const parsed=JSON.parse(body);const response=await fetch("/api/admin/affiliate/content",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({contentKey:key,contentType:type,body:parsed})});const payload=await response.json();setMessage(response.ok?`Draft v${payload.version.version} created.`:payload.error);if(response.ok){setKey("");setBody('{"body":""}');await load();}}catch{setMessage("Body must be valid JSON.");}}
  async function transition(versionId:string,action:string){const input:Record<string,string|number>={versionId,action};if(action==="schedule")input.scheduleInMinutes=60;const response=await fetch("/api/admin/affiliate/content",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(input)});const payload=await response.json();setMessage(response.ok?`${action} completed.`:payload.error);if(response.ok)await load();}
  return <div className="mt-8 grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><form onSubmit={create} className="space-y-4 rounded-3xl border border-slate-300 p-6 dark:border-slate-700"><h2 className="text-xl font-semibold">New draft</h2><label className="block text-sm">Content key<input value={key} onChange={(e)=>setKey(e.target.value)} required className="mt-2 w-full rounded-xl border border-slate-400 bg-transparent p-3" /></label><label className="block text-sm">Type<select value={type} onChange={(e)=>setType(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-400 bg-transparent p-3"><option>approved_script</option><option>faq</option><option>training</option><option>telegram_template</option><option>asset_metadata</option></select></label><label className="block text-sm">JSON body<textarea value={body} onChange={(e)=>setBody(e.target.value)} required className="mt-2 min-h-48 w-full rounded-xl border border-slate-400 bg-transparent p-3 font-mono text-xs" /></label><button className="rounded-full bg-slate-950 px-5 py-2 text-white dark:bg-white dark:text-slate-950">Create version</button>{message&&<p role="status" className="text-sm">{message}</p>}</form><section className="space-y-4"><h2 className="text-xl font-semibold">Versions</h2>{items.map((item)=><article key={item.id} className="rounded-3xl border border-slate-300 p-5 dark:border-slate-700"><h3 className="font-semibold">{item.content_key}</h3><p className="text-xs text-slate-500">{item.content_type} · {item.locale}</p>{[...(item.affiliate_content_versions||[])].sort((a,b)=>b.version-a.version).map((version)=><div key={version.id} className="mt-4 rounded-2xl bg-slate-100 p-4 dark:bg-slate-900"><p className="text-sm font-semibold">v{version.version} · {version.status}</p><pre className="mt-2 max-h-28 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(version.body,null,2)}</pre><div className="mt-3 flex flex-wrap gap-2">{version.status==="draft"&&<button onClick={()=>transition(version.id,"approve")} className="rounded-full border px-3 py-1 text-xs">Approve</button>}{version.status==="approved"&&<><button onClick={()=>transition(version.id,"publish")} className="rounded-full border px-3 py-1 text-xs">Publish now</button><button onClick={()=>transition(version.id,"schedule")} className="rounded-full border px-3 py-1 text-xs">Schedule +1h</button></>}</div></div>)}</article>)}</section></div>;
}
