"use client";

import { useEffect,useMemo,useState } from "react";

type Impact={status:string;requires_rule_review:boolean;requires_telegram_sync:boolean};
type Version={id:string;version:number;status:string;body:Record<string,unknown>;publish_at?:string;affiliate_content_impacts?:Impact[]};
type Item={id:string;content_key:string;content_type:string;locale:string;affiliate_content_versions:Version[]};

export default function AffiliateContentEditor(){
  const [items,setItems]=useState<Item[]>([]);const [key,setKey]=useState("");const [type,setType]=useState("approved_script");const [body,setBody]=useState('{"body":""}');const [message,setMessage]=useState("");
  const parsedPreview=useMemo(()=>{try{return JSON.stringify(JSON.parse(body),null,2);}catch{return "Invalid JSON";}},[body]);
  async function load(){const response=await fetch("/api/admin/affiliate/content");const payload=await response.json();setItems(payload.items||[]);}
  useEffect(()=>{let active=true;void fetch("/api/admin/affiliate/content").then((response)=>response.json()).then((payload)=>{if(active)setItems(payload.items||[]);});return()=>{active=false;};},[]);
  async function create(event:React.FormEvent){event.preventDefault();try{const parsed=JSON.parse(body);const response=await fetch("/api/admin/affiliate/content",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({contentKey:key,contentType:type,body:parsed})});const payload=await response.json();setMessage(response.ok?`Draft v${payload.version.version} created.`:payload.error);if(response.ok){setKey("");setBody('{"body":""}');await load();}}catch{setMessage("Body must be valid JSON.");}}
  async function transition(versionId:string,action:string,targetVersionId?:string){const input:Record<string,string|number>={versionId,action};if(action==="schedule")input.scheduleInMinutes=60;if(targetVersionId)input.targetVersionId=targetVersionId;const response=await fetch("/api/admin/affiliate/content",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(input)});const payload=await response.json();setMessage(response.ok?`${action.replaceAll("_"," ")} completed.`:payload.error);if(response.ok)await load();}
  function exportJson(){const blob=new Blob([JSON.stringify({program:"secwyn-india",items},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download="secwyn-affiliate-content-preview.json";anchor.click();URL.revokeObjectURL(url);}
  async function importJson(file:File){try{const input=JSON.parse(await file.text()) as {contentKey?:string;contentType?:string;body?:Record<string,unknown>};if(!input.contentKey||!input.body)throw new Error();setKey(input.contentKey);setType(input.contentType||"approved_script");setBody(JSON.stringify(input.body,null,2));setMessage("Import loaded as an unpublished draft. Review before saving.");}catch{setMessage("Import must contain contentKey and body JSON fields.");}}
  return <div className="mt-8 grid gap-8 lg:grid-cols-[.85fr_1.15fr]"><div className="space-y-5"><form onSubmit={create} className="space-y-4 rounded-3xl border border-slate-300 p-6 dark:border-slate-700"><h2 className="text-xl font-semibold">New versioned draft</h2><label className="block text-sm">Content key<input value={key} onChange={(event)=>setKey(event.target.value)} required className="mt-2 w-full rounded-xl border border-slate-400 bg-transparent p-3"/></label><label className="block text-sm">Content type<select value={type} onChange={(event)=>setType(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-400 bg-transparent p-3"><option value="faq">FAQ</option><option value="training">Training</option><option value="recruitment_copy">Recruitment copy</option><option value="telegram_template">Telegram template</option><option value="anti_scam">Anti-scam</option><option value="attribution">Attribution</option><option value="activation">Activation</option><option value="commission_explanation">Commission explanation</option><option value="application_pending">Application pending</option><option value="resource_link">Resource link</option><option value="approved_script">Approved script</option></select></label><label className="block text-sm">Structured JSON body<textarea value={body} onChange={(event)=>setBody(event.target.value)} required className="mt-2 min-h-48 w-full rounded-xl border border-slate-400 bg-transparent p-3 font-mono text-xs"/></label><div className="flex flex-wrap gap-2"><button className="rounded-full bg-slate-950 px-5 py-2 text-sm font-semibold text-white dark:bg-white dark:text-slate-950">Create draft</button><label className="cursor-pointer rounded-full border px-5 py-2 text-sm">Import JSON<input type="file" accept="application/json" className="sr-only" onChange={(event)=>{const file=event.target.files?.[0];if(file)void importJson(file);}}/></label></div></form><section className="rounded-3xl border border-slate-300 p-6 dark:border-slate-700"><h2 className="font-semibold">Draft preview</h2><pre className="mt-3 max-h-80 overflow-auto whitespace-pre-wrap break-words rounded-2xl bg-slate-100 p-4 text-xs dark:bg-slate-900">{parsedPreview}</pre></section></div>
    <section className="space-y-4"><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-semibold">Content lifecycle</h2><p className="mt-1 text-xs text-slate-500">Draft → Impact Review → Approve → Publish → Render → Rollback Draft</p></div><button onClick={exportJson} className="rounded-full border px-4 py-2 text-xs">Export JSON</button></div>{message&&<p className="rounded-2xl border border-slate-300 p-3 text-sm dark:border-slate-700">{message}</p>}{items.map((item)=>{const versions=[...(item.affiliate_content_versions||[])].sort((a,b)=>b.version-a.version);return <article key={item.id} className="rounded-3xl border border-slate-300 p-5 dark:border-slate-700"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold">{item.content_key}</h3><p className="text-xs text-slate-500">{item.content_type} · {item.locale} · Program → India → Runtime channels</p></div></div>{versions.map((version,index)=>{const impact=version.affiliate_content_impacts?.[0];const prior=versions[index+1];return <div key={version.id} className="mt-4 rounded-2xl bg-slate-100 p-4 text-sm dark:bg-slate-900"><div className="flex flex-wrap items-center justify-between gap-3"><p>v{version.version} · <span className="capitalize">{version.status.replaceAll("_"," ")}</span></p><div className="flex flex-wrap gap-2">{impact&&impact.status!=="reviewed"&&<button onClick={()=>transition(version.id,"resolve_impact")} className="rounded-full border px-3 py-1 text-xs">Resolve impact</button>}{version.status==="draft"&&<button onClick={()=>transition(version.id,"approve")} className="rounded-full border px-3 py-1 text-xs">Approve</button>}{version.status==="approved"&&<><button onClick={()=>transition(version.id,"publish")} className="rounded-full border px-3 py-1 text-xs">Publish now</button><button onClick={()=>transition(version.id,"schedule")} className="rounded-full border px-3 py-1 text-xs">Schedule +1h</button></>}{version.status==="published"&&<><button onClick={()=>transition(version.id,"retire")} className="rounded-full border px-3 py-1 text-xs">Emergency deprecate</button>{prior&&<button onClick={()=>transition(version.id,"rollback",prior.id)} className="rounded-full border px-3 py-1 text-xs">Rollback draft</button>}</>}</div></div><pre className="mt-3 max-h-44 overflow-auto whitespace-pre-wrap break-words text-xs text-slate-600 dark:text-slate-300">{JSON.stringify(version.body,null,2)}</pre></div>;})}</article>;})}</section></div>;
}
